## Cleaning and treating categorical variables

In [1]:
import numpy as np
from pandas import DataFrame

from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [3]:
data = {'names':['steve', 'john', 'richard', 'sarah', 'randy', 'micheal', 'julie'],
'age':[20, 22, 20, 21, 24, 23, 22],
'gender':['Male', 'Male', np.nan, 'Female', np.nan, 'Male', np.nan],
'rank':[2, 1, 4, 5, 3, 7, 6]}

df = DataFrame(data)
df

     names  age  gender  rank
0    steve   20    Male     2
1     john   22    Male     1
2  richard   20     NaN     4
3    sarah   21  Female     5
4    randy   24     NaN     3
5  micheal   23    Male     7
6    julie   22     NaN     6

### Dropping the column

In [4]:
df = df.drop('gender', axis = 1)
df

     names  age  rank
0    steve   20     2
1     john   22     1
2  richard   20     4
3    sarah   21     5
4    randy   24     3
5  micheal   23     7
6    julie   22     6

### Label Encoding

### One Hot Encoder